Copy of the sign up page is finished
RaminMammadzada/html-forms pull request #3
Opened 2020-06-04 22:58 UTC by RaminMammadzada

- Sign up button created.
- Icons for apps are created.
- User form is created.
- Footer part of the page is created.

2020-06-05 08:53 UTC, peterrobert commented
### PROJECT UNDER REVIEW BY PETER ROBERT

2020-06-05 09:56 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: 
@RaminMammadzada AND @Rocio01  **GREAT PROGRESS ** :clap: 

Very impressive work :clap:  You have a descriptive readme file :+1:  but needs a little improvement. You have a descriptive pull request :+1:  but needs a bit of improvement.

However, there are somethings in the project that are preventing me from approving this project kindly make the changes on the following requirements

- [ ] You need to add a screenshot of the exact display of your project. It seems the screenshot you added in the readme file does not resemble your work kindly rectify that.

- [ ] You need to add a header to your pull request messages like described [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)

- [ ] Your HTML file. It has some errors please validate and fix the errors shown.
![fix html error](https://user-images.githubusercontent.com/32361963/83863222-b88e7e80-a72b-11ea-82e5-360465c0097a.jpg)

Kindly resubmit after you have done the rectifications :smile: 

**HAPPY CODING** :computer:

2020-06-05 09:56 UTC, peterrobert commented on index.html
> +	</footer>
- [ ] Kindly position the footer well. It should be below the form check the clone [here](https://accounts.intuit.com/signup.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dhero_sign_up_free_ProspectWeb%26ivid%3D4a885530-b000-4cdf-a17c-2d54f4c5af9d%26adobe_mc%3DMCORGID%253D969430F0543F253D0A4C98C6%252540AdobeOrg%257CTS%253D1591349552%26ivid%3D4a885530-b000-4cdf-a17c-2d54f4c5af9d)
 In your project its a bit off. 
![form foote](https://user-images.githubusercontent.com/32361963/83861101-d9090980-a728-11ea-8d51-1d59e4f7b110.jpg)

2020-06-05 09:56 UTC, peterrobert commented on index.html
> +		</div>
- [ ] Kindly make the form look similar to the [clone](https://accounts.intuit.com/signup.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dhero_sign_up_free_ProspectWeb%26ivid%3D4a885530-b000-4cdf-a17c-2d54f4c5af9d%26adobe_mc%3DMCORGID%253D969430F0543F253D0A4C98C6%252540AdobeOrg%257CTS%253D1591349552%26ivid%3D4a885530-b000-4cdf-a17c-2d54f4c5af9d)
in your project the form is shrinked 
![shrink](https://user-images.githubusercontent.com/32361963/83861568-677d8b00-a729-11ea-9fc1-a2519367ea87.jpg)

2020-06-06 01:22 UTC, voscarmv commented
# Pull Request Under Review by Oscar Mier (TSE) 👨‍💻 🐦

2020-06-06 01:30 UTC, voscarmv approved these changes
# Excellent work applying the requested changes team! It's a ✔️Yes ✔️ for me! 😄 👍 

**[OPTIONAL]** I strongly recommend you fix the *Live Demo Link* on your `README.md` file! 👀 

Potential employers might be watching, and you definitely want them to be able to look at your work!

**[OPTIONAL]** Try using fonts that are similar to the original. It's not required, but it will give potential employers a better impression if they come around to look at your github! 👨‍💼 👩‍💼 

Other than that, it's all good 👍 

# Comments? Questions? Contact me on [Twitter](http://www.twitter.com/voscarmv) or [LinkedIn](http://www.linkedin.com/in/oscar-mier) 🧑‍💻 🗨️ 🧑‍💻 

## Happy Coding! 🧠 ⌨️ 💻

2020-06-17 08:36 UTC, merged